[features]
seeds = true
skip-lint = false
[programs.localnet]
spl_transfer = "h9gqsge8CFzo2gajMwkUrWWp4RkX6xB6rrrQMhJfBkN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
